import builtins from './builtins.json' with { type: 'json' };
import type { MaterialDef, Models } from './materials.ts';

// Sections of the library, in order; the user's own materials come after them. The anisotropic constituents of
// spr-forge's library (n_o / n_e of liquid crystals and crystals) are left out: this app computes isotropic stacks.
export const MATERIAL_GROUPS = ['Media and glasses', 'Dielectrics', 'Metals', 'Semiconductors', '2D materials'];
export const USER_GROUP = 'Your materials';

// refractiveindex.info data (generated by spr-forge's scripts/gen-builtins.ts).
export const BUILTINS = (builtins as MaterialDef[]).filter((m) => MATERIAL_GROUPS.includes(m.group ?? ''));

export type Library = Map<string, MaterialDef>;

export const makeLibrary = (user: MaterialDef[]): Library => new Map([...BUILTINS, ...user].map((m) => [m.id, m]));

export const groupOf = (m: MaterialDef) => (m.builtin ? (m.group ?? 'Dielectrics') : USER_GROUP);

export const modelsOf = (lib: Library): Models => Object.fromEntries([...lib].map(([id, d]) => [id, d.model]));
